version: '3'
services:
  web:
    tty : true
    build : .
    ports:
     - "8080:9090"
    volumes: 
     - ./:/home/Auto_Coaching/
  db:
    image: mysql:latest
    ports:
     - "3306:3306"
    environment:
     - MYSQL_ROOT_PASSWORD=
     - MYSQL_ALLOW_EMPTY_PASSWORD=true
     - MYSQL_RANDOM_ROOT_PASSWORD=false
